export const URL_API = 'https://oauth.reddit.com';
export const URL_AUTH = 'https://www.reddit.com/api/v1/authorize?';
export const URL_BEST = 'https://www.reddit.com/best/authorize?';
export const URL_POSTS = 'https://www.reddit.com/comments/article/authorize?';
export const CLIENT_ID = 'SyWkxadeYvszrRVT9pCX5Q';
export const RESPONSE_TYPE = 'token';
export const RANDOM_STRING = 'random_string';
export const REDIRECT_URI = 'http://localhost:3000/auth';
export const SCOPE = 'identity submit read';
